
services:
  postgres:
    image: postgres:16-alpine
    container_name: retich_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: retich_app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
